=== robert-paraschiv/Facultate_INF/Tehnologii Web/Proiect/Tema3/fisa_inscriere.dtd
<?xml encoding="UTF-8"?>
<!ELEMENT FISA-INSCRIERE (STUDENT)>
<!ATTLIST FISA-INSCRIERE xmlns CDATA #FIXED ''>
<!ELEMENT STUDENT (CNP,NUME,INITIALA-TATA,DATE-CONTACT,DOMICILIU,
                   OPTIUNI-ADMITERE,DATA-COMPLETARII,MEDIA-BAC)>
<!ATTLIST STUDENT xmlns CDATA #FIXED ''>
<!ELEMENT CNP (#PCDATA)>
<!ATTLIST CNP xmlns CDATA #FIXED ''>
<!ELEMENT NUME (#PCDATA)>
<!ATTLIST NUME xmlns CDATA #FIXED ''>
<!ELEMENT INITIALA-TATA (#PCDATA)>
<!ATTLIST INITIALA-TATA xmlns CDATA #FIXED ''>
<!ELEMENT DATE-CONTACT (NUMAR-TELEFON,ADRESA-EMAIL)>
<!ATTLIST DATE-CONTACT xmlns CDATA #FIXED ''>
<!ELEMENT DOMICILIU (TARA,JUDET,ORAS,ADRESA)>
<!ATTLIST DOMICILIU xmlns CDATA #FIXED ''>
<!ELEMENT OPTIUNI-ADMITERE (OPTIUNE)+>
<!ATTLIST OPTIUNI-ADMITERE xmlns CDATA #FIXED ''>
<!ELEMENT DATA-COMPLETARII (#PCDATA)>
<!ATTLIST DATA-COMPLETARII xmlns CDATA #FIXED ''>
<!ELEMENT MEDIA-BAC (#PCDATA)>
<!ATTLIST MEDIA-BAC xmlns CDATA #FIXED ''>
<!ELEMENT NUMAR-TELEFON (#PCDATA)>
<!ATTLIST NUMAR-TELEFON xmlns CDATA #FIXED ''>
<!ELEMENT ADRESA-EMAIL (#PCDATA)>
<!ATTLIST ADRESA-EMAIL xmlns CDATA #FIXED ''>
<!ELEMENT TARA (#PCDATA)>
<!ATTLIST TARA xmlns CDATA #FIXED ''>
<!ELEMENT JUDET (#PCDATA)>
<!ATTLIST JUDET xmlns CDATA #FIXED ''>
<!ELEMENT ORAS (#PCDATA)>
<!ATTLIST ORAS xmlns CDATA #FIXED ''>
<!ELEMENT ADRESA (#PCDATA)>
<!ATTLIST ADRESA xmlns CDATA #FIXED ''>
<!ELEMENT OPTIUNE (#PCDATA)>
<!ATTLIST OPTIUNE xmlns CDATA #FIXED ''>

=== robert-paraschiv/Facultate_INF/Tehnologii Web/Proiect/Tema3/fisa_inscriere.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE FISA-INSCRIERE SYSTEM "fisa_inscriere.dtd"> -->
<FISA-INSCRIERE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fisa_inscriere.xsd">
    <STUDENT>
        <CNP>1234567890123</CNP>
        <NUME>Robert Paraschiv</NUME>
        <INITIALA-TATA>M</INITIALA-TATA>

        <DATE-CONTACT>
            <NUMAR-TELEFON>0756894556</NUMAR-TELEFON>
            <ADRESA-EMAIL>robertparaschiv@mail.com</ADRESA-EMAIL>
        </DATE-CONTACT>

        <DOMICILIU>
            <TARA>Romania</TARA>
            <JUDET>DOLJ</JUDET>
            <ORAS>Craiova</ORAS>
            <ADRESA>Calea Bucuresti, Nr 23</ADRESA>
        </DOMICILIU>

        <OPTIUNI-ADMITERE>
            <OPTIUNE>Informatica</OPTIUNE>
            <OPTIUNE>Matematica-Informatica</OPTIUNE>
        </OPTIUNI-ADMITERE>

        <DATA-COMPLETARII>2021-03-21</DATA-COMPLETARII>

        <MEDIA-BAC>8.25</MEDIA-BAC>
    </STUDENT>
</FISA-INSCRIERE>
